In [1]:
from dataset.repository import read_df_aapl

df = read_df_aapl()
df

shape: (2_515, 6)
┌────────────┬─────────┬─────────┬──────────┬─────────┬───────────┐
│ Date       ┆ Open    ┆ High    ┆ Low      ┆ Close   ┆ Volume    │
│ ---        ┆ ---     ┆ ---     ┆ ---      ┆ ---     ┆ ---       │
│ date       ┆ f64     ┆ f64     ┆ f64      ┆ f64     ┆ i64       │
╞════════════╪═════════╪═════════╪══════════╪═════════╪═══════════╡
│ 2015-02-26 ┆ 32.1962 ┆ 32.7175 ┆ 31.6525  ┆ 32.6037 ┆ 364687320 │
│ 2015-02-27 ┆ 32.5    ┆ 32.6425 ┆ 32.06    ┆ 32.115  ┆ 247725400 │
│ 2015-03-02 ┆ 32.3125 ┆ 32.57   ┆ 32.075   ┆ 32.2725 ┆ 192170720 │
│ 2015-03-03 ┆ 32.24   ┆ 32.38   ┆ 32.0225  ┆ 32.34   ┆ 150999600 │
│ 2015-03-04 ┆ 32.275  ┆ 32.39   ┆ 32.08    ┆ 32.135  ┆ 126353920 │
│ …          ┆ …       ┆ …       ┆ …        ┆ …       ┆ …         │
│ 2025-02-19 ┆ 244.66  ┆ 246.01  ┆ 243.1604 ┆ 244.87  ┆ 32204220  │
│ 2025-02-20 ┆ 244.94  ┆ 246.78  ┆ 244.29   ┆ 245.83  ┆ 32316910  │
│ 2025-02-21 ┆ 245.95  ┆ 248.69  ┆ 245.22   ┆ 245.55  ┆ 53197430  │
│ 2025-02-24 ┆ 244.925 ┆ 248.86  ┆ 244.42   ┆ 247.1   ┆ 51326400  │
│ 2025-02-25 ┆ 248.0   ┆ 250.0   ┆ 244.91   ┆ 247.04  ┆ 48013270  │
└────────────┴─────────┴─────────┴──────────┴─────────┴───────────┘

In [2]:
from fixture.factory.feature.ofs_ohlcv import factory_ofs_ohlcv

ofs_ohlcv = factory_ofs_ohlcv()
ofs_ohlcv

shape: (3, 6)
┌────────────┬─────────────┬─────────────┬──────────────┬────────────┬────────────┐
│ Date       ┆ OpenOfs     ┆ HighOfs     ┆ LowOfs       ┆ CloseOfs   ┆ VolumeOfs  │
│ ---        ┆ ---         ┆ ---         ┆ ---          ┆ ---        ┆ ---        │
│ date       ┆ f64         ┆ f64         ┆ f64          ┆ f64        ┆ f64        │
╞════════════╪═════════════╪═════════════╪══════════════╪════════════╪════════════╡
│ 2000-01-02 ┆ 6931.471806 ┆ 487.901642  ┆ -512.932944  ┆ 198.026273 ┆ 953.101798 │
│ 2000-01-03 ┆ 4054.651081 ┆ 1397.619424 ┆ -1625.189295 ┆ 295.588022 ┆ 870.11377  │
│ 2000-01-04 ┆ 2876.820725 ┆ 1823.215568 ┆ -2231.435513 ┆ 392.207132 ┆ 800.427077 │
└────────────┴─────────────┴─────────────┴──────────────┴────────────┴────────────┘

In [3]:
import numpy as np

# 対数リターンの研究
print(ofs_ohlcv["OpenOfs"][0])
print(np.log(2))
print(np.log(0.5))
print(np.log(2) * 100)
print(np.log(1.1))
print(np.log(1.1) * 100)
print(np.log(1.2))
print(np.log(0.1))
print(np.log(10))
print(np.log(1.001))
print(np.log(0.999))
print(np.log(1.001) * 10000)

6931.471805599453
0.6931471805599453
-0.6931471805599453
69.31471805599453
0.09531017980432493
9.531017980432493
0.1823215567939546
-2.3025850929940455
2.302585092994046
0.0009995003330834232
-0.0010005003335835344
9.995003330834232

In [4]:
# 対数比の挙動
print(1, '\t', np.log(101/100) * 100)
print(10, '\t', np.log(110/100) * 100)
print(25, '\t', np.log(125/100) * 100)
print(50, '\t', np.log(150/100) * 100)
print(100, '\t', np.log(200/100) * 100)
print(400, '\t', np.log(400/100) * 100)

1 	 0.9950330853168092
10 	 9.531017980432493
25 	 22.314355131420978
50 	 40.546510810816436
100 	 69.31471805599453
400 	 138.62943611198907

In [5]:
import pandas_ta as ta

# カスタム戦略を作成
my_strategy = ta.Strategy(
    name="基本指標",
    ta=[
        # trend
        {"kind": "sma", "length": 5},
        {"kind": "sma", "length": 25},
        {"kind": "sma", "length": 75},
        # momentum
        {"kind": "rsi"},
        {"kind": "roc"},
        # volatility
        {"kind": "atr"},
        {"kind": "bbands"},
        # volume
        {"kind": "obv"},
        {"kind": "vwap"},
    ]
)

# 戦略を適用
df.ta.strategy(my_strategy)
df[75:]

ModuleNotFoundError: No module named 'pandas_ta'