In [4]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.01 ┆ 99.52  ┆ 99.77  ┆ 30920  │
│ 2000-01-02 00:00:00 ┆ 99.77  ┆ 99.99  ┆ 99.64  ┆ 99.77  ┆ 19171  │
│ 2000-01-03 00:00:00 ┆ 99.77  ┆ 100.86 ┆ 99.48  ┆ 100.6  ┆ 15764  │
│ 2000-01-04 00:00:00 ┆ 99.59  ┆ 101.09 ┆ 99.51  ┆ 100.8  ┆ 21760  │
│ 2000-01-05 00:00:00 ┆ 100.8  ┆ 101.26 ┆ 100.48 ┆ 100.63 ┆ 27977  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 109.35 ┆ 109.43 ┆ 108.21 ┆ 108.32 ┆ 24372  │
│ 2000-04-06 00:00:00 ┆ 108.32 ┆ 108.59 ┆ 108.17 ┆ 108.21 ┆ 38189  │
│ 2000-04-07 00:00:00 ┆ 108.21 ┆ 108.99 ┆ 107.84 ┆ 108.98 ┆ 14394  │
│ 2000-04-08 00:00:00 ┆ 107.89 ┆ 110.35 ┆ 107.77 ┆ 110.05 ┆ 29827  │
│ 2000-04-09 00:00:00 ┆ 110.05 ┆ 110.39 ┆ 109.67 ┆ 109.75 ┆ 18673  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [5]:
import plotly.express as px

fig = px.line(df, x="Date", y="Close")
fig.show()

In [8]:
import pandas_ta as ta
import polars as pl

# Date列をインデックスに設定
pandas_df = df.to_pandas().set_index('Date')
print(pandas_df)

# カスタム戦略を作成
my_strategy = ta.Strategy(
    name="基本指標",
    ta=[
        # trend
        {"kind": "sma", "length": 5},
        {"kind": "sma", "length": 25},
        {"kind": "sma", "length": 75},
        # momentum
        {"kind": "rsi"},
        {"kind": "roc"},
        # volatility
        {"kind": "atr"},
        {"kind": "bbands"},
        # volume
        {"kind": "obv"},
        {"kind": "vwap"},
    ]
)

# 戦略を適用
pandas_df.ta.strategy(my_strategy)
print(pandas_df[75:])

ta_pldf = pl.from_pandas(pandas_df[75:].reset_index())
ta_pldf

              Open    High     Low   Close  Volume
Date
2000-01-01  101.00  101.01   99.52   99.77   30920
2000-01-02   99.77   99.99   99.64   99.77   19171
2000-01-03   99.77  100.86   99.48  100.60   15764
2000-01-04   99.59  101.09   99.51  100.80   21760
2000-01-05  100.80  101.26  100.48  100.63   27977
...            ...     ...     ...     ...     ...
2000-04-05  109.35  109.43  108.21  108.32   24372
2000-04-06  108.32  108.59  108.17  108.21   38189
2000-04-07  108.21  108.99  107.84  108.98   14394
2000-04-08  107.89  110.35  107.77  110.05   29827
2000-04-09  110.05  110.39  109.67  109.75   18673

[100 rows x 5 columns]
              Open    High     Low   Close  Volume    SMA_5    SMA_25  \
Date
2000-03-16   97.78   98.02   96.83   96.98   34263   96.660   97.0240
2000-03-17   96.98   98.58   96.64   98.44   26563   97.166   96.9844
2000-03-18   98.44   98.94   98.31   98.70   37100   97.554   96.9532
2000-03-19   97.72   99.39   97.42   99.14   36589   98.014   97.0032
2000-03-20   99.14  100.28   98.96  100.14   24249   98.680   97.0720
2000-03-21  101.14  101.40   99.72   99.96   15759   99.276   97.1236
2000-03-22   99.96  100.55   99.64  100.43   13737   99.674   97.2144
2000-03-23  100.43  101.47  100.14  101.24   20228  100.182   97.3280
2000-03-24  100.23  101.81  100.10  101.58   18729  100.670   97.5260
2000-03-25  101.58  102.59  101.36  102.28   49702  101.098   97.7176
2000-03-26  103.31  103.52  102.16  102.44   24519  101.594   97.9140
2000-03-27  102.44  104.35  102.18  104.09   14414  102.326   98.1844
2000-03-28  104.09  104.43  103.89  104.24   47068  102.926   98.4972
2000-03-29  103.20  104.37  102.93  104.13   13739  103.436   98.7964
2000-03-30  104.13  104.38  103.73  104.04   25898  103.788   99.1196
2000-03-31  105.08  105.56  104.87  105.42   31573  104.384   99.4400
2000-04-01  105.42  106.20  105.37  105.94   35855  104.754   99.8280
2000-04-02  105.94  107.07  105.62  106.76   28552  105.258  100.3140
2000-04-03  105.69  107.45  105.44  107.16   44043  105.864  100.7768
2000-04-04  107.16  108.31  107.01  108.27   49121  106.710  101.3356
2000-04-05  109.35  109.43  108.21  108.32   24372  107.290  101.8408
2000-04-06  108.32  108.59  108.17  108.21   38189  107.744  102.3328
2000-04-07  108.21  108.99  107.84  108.98   14394  108.188  102.8216
2000-04-08  107.89  110.35  107.77  110.05   29827  108.766  103.3500
2000-04-09  110.05  110.39  109.67  109.75   18673  109.062  103.8676

                SMA_75     RSI_14    ROC_10   ATRr_14   BBL_5_2.0  BBM_5_2.0  \
Date
2000-03-16  100.716267  47.258519 -0.441433  1.294229   95.895906     96.660
2000-03-17  100.698533  54.764660  2.285952  1.340521   95.883652     97.166
2000-03-18  100.673200  55.966516  4.323010  1.289601   95.882804     97.554
2000-03-19  100.651067  58.000211  3.713778  1.338351   96.129597     98.014
2000-03-20  100.644533  62.265721  6.193001  1.337037   96.622584     98.680
2000-03-21  100.618133  61.063558  4.462326  1.361599   97.930334     99.276
2000-03-22  100.612267  63.068584  4.712752  1.329262   98.376519     99.674
2000-03-23  100.606133  66.290323  4.630012  1.329315   98.820330    100.182
2000-03-24  100.604267  67.569205  4.894672  1.356565   99.406481    100.670
2000-03-25  100.611600  70.085499  5.650243  1.347507   99.450971    101.098
2000-03-26  100.613867  70.646128  5.630027  1.348401  100.133392    101.594
2000-03-27  100.643867  75.703130  5.739537  1.407187  100.353647    102.326
2000-03-28  100.680267  76.106131  5.612969  1.345146  100.819492    102.926
2000-03-29  100.700133  75.122098  5.033286  1.351932  101.673248    103.436
2000-03-30  100.730133  74.275899  3.894548  1.301725  102.433576    103.788
2000-03-31  100.766667  78.310303  5.462185  1.317336  103.339655    104.384
2000-04-01  100.806800  79.608098  5.486408  1.282485  103.201320    104.754
2000-04-02  100.857600  81.489044  5.452390  1.294464  103.159757    105.258
2000-04-03  100.915867  82.344560  5.493207  1.345625  103.670862    105.864
2000-04-04  100.975467  84.487148  5.856472  1.342363  104.730990    106.710
2000-04-05  101.046000  84.577937  5.739945  1.333615  105.469758    107.290
2000-04-06  101.105467  83.421222  3.958113  1.268304  106.437120    107.744
2000-04-07  101.176533  84.970718  4.547199  1.259847  107.018836    108.188
2000-04-08  101.264133  86.814882  5.685201  1.354210  107.366423    108.766
2000-04-09  101.335600  83.713336  5.488274  1.308880  107.583439    109.062

             BBU_5_2.0  BBB_5_2.0  BBP_5_2.0       OBV      VWAP_D
Date
2000-03-16   97.424094   1.580994   0.709398   42255.0   97.276667
2000-03-17   98.448348   2.639499   0.996745   68818.0   97.886667
2000-03-18   99.225196   3.426197   0.842868  105918.0   98.650000
2000-03-19   99.898403   3.845172   0.798768  142507.0   98.650000
2000-03-20  100.737416   4.169874   0.854814  166756.0   99.793333
2000-03-21  100.621666   2.710959   0.754149  150997.0  100.360000
2000-03-22  100.971481   2.603449   0.791334  164734.0  100.206667
2000-03-23  101.543670   2.718392   0.888494  184962.0  100.950000
2000-03-24  101.933519   2.510219   0.860105  203691.0  101.163333
2000-03-25  102.745029   3.258282   0.858828  253393.0  102.076667
2000-03-26  103.054608   2.875383   0.789605  277912.0  102.706667
2000-03-27  104.298353   3.855038   0.947182  292326.0  103.540000
2000-03-28  105.032508   4.093248   0.811891  339394.0  104.186667
2000-03-29  105.198752   3.408392   0.696851  325655.0  103.810000
2000-03-30  105.142424   2.609982   0.593028  299757.0  104.050000
2000-03-31  105.428345   2.000967   0.996005  331330.0  105.283333
2000-04-01  106.306680   2.964431   0.881920  367185.0  105.836667
2000-04-02  107.356243   3.986857   0.857918  395737.0  106.483333
2000-04-03  108.057138   4.143313   0.795467  439780.0  106.683333
2000-04-04  108.689010   3.709137   0.894136  488901.0  107.863333
2000-04-05  109.110242   3.393125   0.782929  513273.0  108.653333
2000-04-06  109.050880   2.425899   0.678287  475084.0  108.323333
2000-04-07  109.357164   2.161356   0.838704  489478.0  108.603333
2000-04-08  110.165577   2.573556   0.958710  519305.0  109.390000
2000-04-09  110.540561   2.711415   0.732659  500632.0  109.936667

shape: (25, 19)
┌──────────────┬────────┬────────┬────────┬───┬───────────┬───────────┬──────────┬────────────┐
│ Date         ┆ Open   ┆ High   ┆ Low    ┆ … ┆ BBB_5_2.0 ┆ BBP_5_2.0 ┆ OBV      ┆ VWAP_D     │
│ ---          ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---        │
│ datetime[μs] ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64       ┆ f64       ┆ f64      ┆ f64        │
╞══════════════╪════════╪════════╪════════╪═══╪═══════════╪═══════════╪══════════╪════════════╡
│ 2000-03-16   ┆ 97.78  ┆ 98.02  ┆ 96.83  ┆ … ┆ 1.580994  ┆ 0.709398  ┆ 42255.0  ┆ 97.276667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-03-17   ┆ 96.98  ┆ 98.58  ┆ 96.64  ┆ … ┆ 2.639499  ┆ 0.996745  ┆ 68818.0  ┆ 97.886667  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-03-18   ┆ 98.44  ┆ 98.94  ┆ 98.31  ┆ … ┆ 3.426197  ┆ 0.842868  ┆ 105918.0 ┆ 98.65      │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-03-19   ┆ 97.72  ┆ 99.39  ┆ 97.42  ┆ … ┆ 3.845172  ┆ 0.798768  ┆ 142507.0 ┆ 98.65      │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-03-20   ┆ 99.14  ┆ 100.28 ┆ 98.96  ┆ … ┆ 4.169874  ┆ 0.854814  ┆ 166756.0 ┆ 99.793333  │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ …            ┆ …      ┆ …      ┆ …      ┆ … ┆ …         ┆ …         ┆ …        ┆ …          │
│ 2000-04-05   ┆ 109.35 ┆ 109.43 ┆ 108.21 ┆ … ┆ 3.393125  ┆ 0.782929  ┆ 513273.0 ┆ 108.653333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-04-06   ┆ 108.32 ┆ 108.59 ┆ 108.17 ┆ … ┆ 2.425899  ┆ 0.678287  ┆ 475084.0 ┆ 108.323333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-04-07   ┆ 108.21 ┆ 108.99 ┆ 107.84 ┆ … ┆ 2.161356  ┆ 0.838704  ┆ 489478.0 ┆ 108.603333 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-04-08   ┆ 107.89 ┆ 110.35 ┆ 107.77 ┆ … ┆ 2.573556  ┆ 0.95871   ┆ 519305.0 ┆ 109.39     │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2000-04-09   ┆ 110.05 ┆ 110.39 ┆ 109.67 ┆ … ┆ 2.711415  ┆ 0.732659  ┆ 500632.0 ┆ 109.936667 │
│ 00:00:00     ┆        ┆        ┆        ┆   ┆           ┆           ┆          ┆            │
└──────────────┴────────┴────────┴────────┴───┴───────────┴───────────┴──────────┴────────────┘