In [1]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.22 ┆ 99.36  ┆ 99.47  ┆ 17342  │
│ 2000-01-02 00:00:00 ┆ 99.47  ┆ 100.63 ┆ 99.17  ┆ 100.39 ┆ 13467  │
│ 2000-01-03 00:00:00 ┆ 100.39 ┆ 101.08 ┆ 100.2  ┆ 100.92 ┆ 48941  │
│ 2000-01-04 00:00:00 ┆ 99.92  ┆ 100.54 ┆ 99.78  ┆ 100.23 ┆ 13400  │
│ 2000-01-05 00:00:00 ┆ 100.23 ┆ 100.81 ┆ 100.1  ┆ 100.39 ┆ 46888  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 108.32 ┆ 108.51 ┆ 108.13 ┆ 108.41 ┆ 48004  │
│ 2000-04-06 00:00:00 ┆ 108.41 ┆ 108.6  ┆ 107.89 ┆ 108.01 ┆ 44029  │
│ 2000-04-07 00:00:00 ┆ 108.01 ┆ 109.37 ┆ 107.89 ┆ 109.13 ┆ 45211  │
│ 2000-04-08 00:00:00 ┆ 108.04 ┆ 109.6  ┆ 107.64 ┆ 109.39 ┆ 21633  │
│ 2000-04-09 00:00:00 ┆ 109.39 ┆ 110.41 ┆ 109.15 ┆ 110.26 ┆ 33827  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [2]:
from feature.closes.service import derive_closes


closes = derive_closes(df, 8)
closes

shape: (91, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ now       ┆ lag_1     ┆ lag_2     ┆ … ┆ lag_5     ┆ lag_6     ┆ lag_7     ┆ lag_8    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ datetime[ ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ μs]       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2000-01-1 ┆ 89.492656 ┆ 51.50056  ┆ -124.3355 ┆ … ┆ 15.950557 ┆ -68.60578 ┆ 52.655231 ┆ 92.06509 │
│ 0         ┆           ┆           ┆ 27        ┆   ┆           ┆ 7         ┆           ┆ 5        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-01-1 ┆ -88.50485 ┆ 89.492656 ┆ 51.50056  ┆ … ┆ -16.94831 ┆ 15.950557 ┆ -68.60578 ┆ 52.65523 │
│ 1         ┆ 5         ┆           ┆           ┆   ┆ 2         ┆           ┆ 7         ┆ 1        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-01-1 ┆ -0.987801 ┆ -88.50485 ┆ 89.492656 ┆ … ┆ 173.10882 ┆ -16.94831 ┆ 15.950557 ┆ -68.6057 │
│ 2         ┆           ┆ 5         ┆           ┆   ┆ 8         ┆ 2         ┆           ┆ 87       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-01-1 ┆ 51.236687 ┆ -0.987801 ┆ -88.50485 ┆ … ┆ -124.3355 ┆ 173.10882 ┆ -16.94831 ┆ 15.95055 │
│ 3         ┆           ┆           ┆ 5         ┆   ┆ 27        ┆ 8         ┆ 2         ┆ 7        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-01-1 ┆ 60.748766 ┆ 51.236687 ┆ -0.987801 ┆ … ┆ 51.50056  ┆ -124.3355 ┆ 173.10882 ┆ -16.9483 │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆ 27        ┆ 8         ┆ 12       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2000-04-0 ┆ 107.57777 ┆ 49.539756 ┆ 34.730405 ┆ … ┆ 70.342495 ┆ 26.745646 ┆ 12.441979 ┆ 139.8354 │
│ 5         ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 43       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-04-0 ┆ -36.96520 ┆ 107.57777 ┆ 49.539756 ┆ … ┆ -34.15887 ┆ 70.342495 ┆ 26.745646 ┆ 12.44197 │
│ 6         ┆ 2         ┆ 9         ┆           ┆   ┆ 2         ┆           ┆           ┆ 9        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-04-0 ┆ 103.16016 ┆ -36.96520 ┆ 107.57777 ┆ … ┆ 107.77188 ┆ -34.15887 ┆ 70.342495 ┆ 26.74564 │
│ 7         ┆ 7         ┆ 2         ┆ 9         ┆   ┆ 8         ┆ 2         ┆           ┆ 6        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-04-0 ┆ 23.79646  ┆ 103.16016 ┆ -36.96520 ┆ … ┆ 34.730405 ┆ 107.77188 ┆ -34.15887 ┆ 70.34249 │
│ 8         ┆           ┆ 7         ┆ 2         ┆   ┆           ┆ 8         ┆ 2         ┆ 5        │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2000-04-0 ┆ 79.21735  ┆ 23.79646  ┆ 103.16016 ┆ … ┆ 49.539756 ┆ 34.730405 ┆ 107.77188 ┆ -34.1588 │
│ 9         ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆ 8         ┆ 72       │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
from feature.closes.derive import derive_closes_n4

closes_n4 = derive_closes_n4(df)
closes_n4

shape: (95, 6)
┌─────────────────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┐
│ Date                ┆ now         ┆ lag_1       ┆ lag_2       ┆ lag_3      ┆ lag_4      │
│ ---                 ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│ datetime[μs]        ┆ f64         ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════════════════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╡
│ 2000-01-06 00:00:00 ┆ -16.948312  ┆ 15.950557   ┆ -68.605787  ┆ 52.655231  ┆ 92.065095  │
│ 2000-01-07 00:00:00 ┆ 173.108828  ┆ -16.948312  ┆ 15.950557   ┆ -68.605787 ┆ 52.655231  │
│ 2000-01-08 00:00:00 ┆ -124.335527 ┆ 173.108828  ┆ -16.948312  ┆ 15.950557  ┆ -68.605787 │
│ 2000-01-09 00:00:00 ┆ 51.50056    ┆ -124.335527 ┆ 173.108828  ┆ -16.948312 ┆ 15.950557  │
│ 2000-01-10 00:00:00 ┆ 89.492656   ┆ 51.50056    ┆ -124.335527 ┆ 173.108828 ┆ -16.948312 │
│ …                   ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          │
│ 2000-04-05 00:00:00 ┆ 107.577779  ┆ 49.539756   ┆ 34.730405   ┆ 107.771888 ┆ -34.158872 │
│ 2000-04-06 00:00:00 ┆ -36.965202  ┆ 107.577779  ┆ 49.539756   ┆ 34.730405  ┆ 107.771888 │
│ 2000-04-07 00:00:00 ┆ 103.160167  ┆ -36.965202  ┆ 107.577779  ┆ 49.539756  ┆ 34.730405  │
│ 2000-04-08 00:00:00 ┆ 23.79646    ┆ 103.160167  ┆ -36.965202  ┆ 107.577779 ┆ 49.539756  │
│ 2000-04-09 00:00:00 ┆ 79.21735    ┆ 23.79646    ┆ 103.160167  ┆ -36.965202 ┆ 107.577779 │
└─────────────────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┘

In [4]:
closes.equals(closes_n4)

False