In [4]:
from fixture.factory.dataset.ohlcv import factory_ohlcv_cycle

df = factory_ohlcv_cycle()
df

shape: (100, 6)
┌─────────────────────┬────────┬────────┬────────┬────────┬────────┐
│ Date                ┆ Open   ┆ High   ┆ Low    ┆ Close  ┆ Volume │
│ ---                 ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ datetime[μs]        ┆ f64    ┆ f64    ┆ f64    ┆ f64    ┆ i64    │
╞═════════════════════╪════════╪════════╪════════╪════════╪════════╡
│ 2000-01-01 00:00:00 ┆ 101.0  ┆ 101.32 ┆ 100.42 ┆ 100.66 ┆ 47420  │
│ 2000-01-02 00:00:00 ┆ 100.66 ┆ 100.83 ┆ 99.95  ┆ 100.0  ┆ 13834  │
│ 2000-01-03 00:00:00 ┆ 100.0  ┆ 100.67 ┆ 99.91  ┆ 100.39 ┆ 31922  │
│ 2000-01-04 00:00:00 ┆ 99.38  ┆ 100.51 ┆ 99.21  ┆ 100.35 ┆ 47830  │
│ 2000-01-05 00:00:00 ┆ 100.35 ┆ 101.02 ┆ 100.07 ┆ 100.73 ┆ 21075  │
│ …                   ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 2000-04-05 00:00:00 ┆ 108.64 ┆ 108.69 ┆ 108.24 ┆ 108.45 ┆ 38910  │
│ 2000-04-06 00:00:00 ┆ 108.45 ┆ 108.67 ┆ 108.21 ┆ 108.52 ┆ 14157  │
│ 2000-04-07 00:00:00 ┆ 108.52 ┆ 108.8  ┆ 107.98 ┆ 108.28 ┆ 12775  │
│ 2000-04-08 00:00:00 ┆ 107.19 ┆ 110.33 ┆ 106.92 ┆ 110.07 ┆ 34777  │
│ 2000-04-09 00:00:00 ┆ 110.07 ┆ 110.11 ┆ 109.39 ┆ 109.7  ┆ 37713  │
└─────────────────────┴────────┴────────┴────────┴────────┴────────┘

In [5]:
from feature.closes.derive import derive_closes_n4


closes = derive_closes_n4(df)
closes

shape: (95, 6)
┌─────────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ Date                ┆ now        ┆ lag_1      ┆ lag_2      ┆ lag_3      ┆ lag_4      │
│ ---                 ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ datetime[μs]        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 2000-01-06 00:00:00 ┆ 0.992704   ┆ 37.795947  ┆ -3.985255  ┆ 38.924147  ┆ -65.783154 │
│ 2000-01-07 00:00:00 ┆ 77.128831  ┆ 0.992704   ┆ 37.795947  ┆ -3.985255  ┆ 38.924147  │
│ 2000-01-08 00:00:00 ┆ -20.707003 ┆ 77.128831  ┆ 0.992704   ┆ 37.795947  ┆ -3.985255  │
│ 2000-01-09 00:00:00 ┆ 55.123675  ┆ -20.707003 ┆ 77.128831  ┆ 0.992704   ┆ 37.795947  │
│ 2000-01-10 00:00:00 ┆ -11.786663 ┆ 55.123675  ┆ -20.707003 ┆ 77.128831  ┆ 0.992704   │
│ …                   ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2000-04-05 00:00:00 ┆ 81.474388  ┆ 130.060313 ┆ -44.166778 ┆ 152.112149 ┆ 5.713742   │
│ 2000-04-06 00:00:00 ┆ 6.452505   ┆ 81.474388  ┆ 130.060313 ┆ -44.166778 ┆ 152.112149 │
│ 2000-04-07 00:00:00 ┆ -22.14023  ┆ 6.452505   ┆ 81.474388  ┆ 130.060313 ┆ -44.166778 │
│ 2000-04-08 00:00:00 ┆ 163.960623 ┆ -22.14023  ┆ 6.452505   ┆ 81.474388  ┆ 130.060313 │
│ 2000-04-09 00:00:00 ┆ -33.671598 ┆ 163.960623 ┆ -22.14023  ┆ 6.452505   ┆ 81.474388  │
└─────────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘