In [1]:
from domain.dataset.ohlcv import read_df_aapl

ohlcv = read_df_aapl()
ohlcv.df

shape: (2_515, 6)
┌─────────────────────┬─────────┬─────────┬──────────┬─────────┬───────────┐
│ Date                ┆ Open    ┆ High    ┆ Low      ┆ Close   ┆ Volume    │
│ ---                 ┆ ---     ┆ ---     ┆ ---      ┆ ---     ┆ ---       │
│ datetime[μs]        ┆ f64     ┆ f64     ┆ f64      ┆ f64     ┆ i64       │
╞═════════════════════╪═════════╪═════════╪══════════╪═════════╪═══════════╡
│ 2015-02-26 00:00:00 ┆ 32.1962 ┆ 32.7175 ┆ 31.6525  ┆ 32.6037 ┆ 364687320 │
│ 2015-02-27 00:00:00 ┆ 32.5    ┆ 32.6425 ┆ 32.06    ┆ 32.115  ┆ 247725400 │
│ 2015-03-02 00:00:00 ┆ 32.3125 ┆ 32.57   ┆ 32.075   ┆ 32.2725 ┆ 192170720 │
│ 2015-03-03 00:00:00 ┆ 32.24   ┆ 32.38   ┆ 32.0225  ┆ 32.34   ┆ 150999600 │
│ 2015-03-04 00:00:00 ┆ 32.275  ┆ 32.39   ┆ 32.08    ┆ 32.135  ┆ 126353920 │
│ …                   ┆ …       ┆ …       ┆ …        ┆ …       ┆ …         │
│ 2025-02-19 00:00:00 ┆ 244.66  ┆ 246.01  ┆ 243.1604 ┆ 244.87  ┆ 32204220  │
│ 2025-02-20 00:00:00 ┆ 244.94  ┆ 246.78  ┆ 244.29   ┆ 245.83  ┆ 32316910  │
│ 2025-02-21 00:00:00 ┆ 245.95  ┆ 248.69  ┆ 245.22   ┆ 245.55  ┆ 53197430  │
│ 2025-02-24 00:00:00 ┆ 244.925 ┆ 248.86  ┆ 244.42   ┆ 247.1   ┆ 51326400  │
│ 2025-02-25 00:00:00 ┆ 248.0   ┆ 250.0   ┆ 244.91   ┆ 247.04  ┆ 48013270  │
└─────────────────────┴─────────┴─────────┴──────────┴─────────┴───────────┘

In [2]:
from fixture.domain.feature.ohlcv_ofs import factory_ohlcv_ofs

ofs_ohlcv = factory_ohlcv_ofs()
ofs_ohlcv.df

shape: (3, 6)
┌─────────────────────┬───────────────┬───────────────┬─────────────┬──────────────┬────────────┐
│ Date                ┆ PrevCloseOfs  ┆ PrevVolumeOfs ┆ HighOfs     ┆ LowOfs       ┆ CloseOfs   │
│ ---                 ┆ ---           ┆ ---           ┆ ---         ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ f64           ┆ f64           ┆ f64         ┆ f64          ┆ f64        │
╞═════════════════════╪═══════════════╪═══════════════╪═════════════╪══════════════╪════════════╡
│ 2000-01-02 00:00:00 ┆ 7029.99477    ┆ 953.101798    ┆ 487.901642  ┆ -512.932944  ┆ 198.026273 │
│ 2000-01-03 00:00:00 ┆ 4152.212831   ┆ 870.11377     ┆ 1397.619424 ┆ -1625.189295 ┆ 295.588022 │
│ 2000-01-04 00:00:00 ┆ -11182.207601 ┆ -1823.215568  ┆ 1723.712259 ┆ -2330.938822 ┆ 0.0        │
└─────────────────────┴───────────────┴───────────────┴─────────────┴──────────────┴────────────┘

In [3]:
ofs_ohlcv.df["Date"].to_list()

[datetime.datetime(2000, 1, 2, 0, 0),
 datetime.datetime(2000, 1, 3, 0, 0),
 datetime.datetime(2000, 1, 4, 0, 0)]

In [4]:
print(ofs_ohlcv.df["PrevCloseOfs"].sum())
print(ofs_ohlcv.df["PrevVolumeOfs"].sum())

0.0
4.547473508864641e-13

In [5]:
from math import log

# 対数リターンの研究
print(ofs_ohlcv.df["PrevCloseOfs"][0])
print(log(2))
print(log(0.5))
print(log(2) * 100)
print(log(1.1))
print(log(1.1) * 100)
print(log(1.2))
print(log(0.1))
print(log(10))
print(log(1.001))
print(log(0.999))
print(log(1.001) * 10000)
print(log(1.001) * 10000)

7029.99477002957
0.6931471805599453
-0.6931471805599453
69.31471805599453
0.09531017980432493
9.531017980432493
0.1823215567939546
-2.3025850929940455
2.302585092994046
0.0009995003330834232
-0.0010005003335835344
9.995003330834232
9.995003330834232

In [6]:
# 対数比の挙動
print(1, "\t", log(101 / 100) * 100)
print(10, "\t", log(110 / 100) * 100)
print(25, "\t", log(125 / 100) * 100)
print(50, "\t", log(150 / 100) * 100)
print(100, "\t", log(200 / 100) * 100)
print(400, "\t", log(400 / 100) * 100)

1 	 0.9950330853168092
10 	 9.531017980432493
25 	 22.314355131420978
50 	 40.546510810816436
100 	 69.31471805599453
400 	 138.62943611198907